import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Atelier Palette — Warm Editorial Fashion
        ivory: {
          50: '#FDFCFA',
          100: '#FAF8F5',
          200: '#F5F0EA',
          300: '#EDE6DB',
          400: '#E0D5C5',
          500: '#D4C9B5',
        },
        charcoal: {
          50: '#F5F5F5',
          100: '#E8E8E8',
          200: '#D1D1D1',
          300: '#A3A3A3',
          400: '#737373',
          500: '#525252',
          600: '#3D3D3D',
          700: '#2E2E2E',
          800: '#1F1F1F',
          900: '#1A1A1A',
          950: '#0D0D0D',
        },
        gold: {
          50: '#FBF7F1',
          100: '#F5ECDE',
          200: '#EBD9BD',
          300: '#DDBF93',
          400: '#CDA46E',
          500: '#B8956A',
          600: '#A07A4E',
          700: '#846142',
          800: '#6D503A',
          900: '#5A4333',
        },
        sage: {
          50: '#F6F7F4',
          100: '#E8EBE2',
          200: '#D1D7C5',
          300: '#B3BDA1',
          400: '#96A380',
          500: '#7A8B66',
        },
        // Semantic
        surface: {
          DEFAULT: 'var(--atl-surface)',
          dim: '#dbd9d9',
          muted: 'var(--atl-surface-muted)',
          elevated: 'var(--atl-surface-elevated)',
          contrast: 'var(--atl-surface-contrast)',
        },
        'surface-dim': '#dbd9d9',
        'aged-gold': '#b8956a',
        dark: '#1A1A1A',
        text: {
          primary: 'var(--atl-text-primary)',
          secondary: 'var(--atl-text-secondary)',
          muted: 'var(--atl-text-muted)',
          inverse: 'var(--atl-text-inverse)',
          accent: 'var(--atl-text-accent)',
        },
        border: {
          DEFAULT: 'var(--atl-border)',
          subtle: 'var(--atl-border-subtle)',
          strong: 'var(--atl-border-strong)',
        },
        accent: {
          DEFAULT: 'var(--atl-accent)',
          hover: 'var(--atl-accent-hover)',
          muted: 'var(--atl-accent-muted)',
        },
        success: {
          DEFAULT: '#2D6A4F',
          bg: '#F0FAF4',
          border: '#B7E4C7',
        },
        warning: {
          DEFAULT: '#B45309',
          bg: '#FFFBEB',
          border: '#FDE68A',
        },
        error: {
          DEFAULT: '#9B2C2C',
          bg: '#FFF5F5',
          border: '#FEB2B2',
        },
      },
      fontFamily: {
        serif: [
          'Cormorant Garamond',
          'Georgia',
          'Cambria',
          'Times New Roman',
          'serif',
        ],
        sans: [
          'Outfit',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        display: [
          'Anton',
          'Bebas Neue',
          'Outfit',
          'sans-serif',
        ],
        syne: [
          'Syne',
          'Outfit',
          'sans-serif',
        ],
      },
      fontSize: {
        // Editorial Scale
        'display-xl': ['5rem', { lineHeight: '0.95', letterSpacing: '-0.03em', fontWeight: '300' }],
        'display-lg': ['3.75rem', { lineHeight: '0.95', letterSpacing: '-0.025em', fontWeight: '300' }],
        'display': ['3rem', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '300' }],
        'heading-xl': ['2.25rem', { lineHeight: '1.1', letterSpacing: '-0.015em', fontWeight: '400' }],
        'heading-lg': ['1.875rem', { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '400' }],
        'heading': ['1.5rem', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '400' }],
        'subheading': ['1.125rem', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['1.0625rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body': ['0.9375rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.5', fontWeight: '400' }],
        'caption': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.04em', fontWeight: '500' }],
        'overline': ['0.6875rem', { lineHeight: '1.2', letterSpacing: '0.15em', fontWeight: '600' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '26': '6.5rem',
        '30': '7.5rem',
        '34': '8.5rem',
        '38': '9.5rem',
      },
      borderRadius: {
        'none': '0',
        'xs': '2px',
        'sm': '4px',
        'DEFAULT': '4px',
        'md': '6px',
        'lg': '8px',
      },
      boxShadow: {
        'subtle': '0 1px 2px rgba(26, 26, 26, 0.04)',
        'soft': '0 2px 8px rgba(26, 26, 26, 0.06)',
        'elevated': '0 4px 16px rgba(26, 26, 26, 0.08)',
        'overlay': '0 8px 32px rgba(26, 26, 26, 0.12)',
      },
      screens: {
        'xs': '375px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1440px',
        '3xl': '1920px',
      },
      maxWidth: {
        'editorial': '1440px',
        'content': '1200px',
        'narrow': '680px',
      },
      transitionTimingFunction: {
        'editorial': 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards',
        'slide-up': 'slideUp 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards',
        'slide-down': 'slideDown 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards',
        'scale-in': 'scaleIn 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
