import { randomUUID } from 'node:crypto';
import argon2 from 'argon2';
import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { app } from '../../src/app.js';
import { getPrismaClient } from '../../src/config/database.js';
import { CSRF_COOKIE } from '../../src/utils/auth.js';

const prisma=getPrismaClient(); const password='SecurePassword123'; const adminEmail=`admin-${randomUUID()}@example.invalid`; const customerEmail=`customer-${randomUUID()}@example.invalid`;
let adminId=''; let customerId=''; let variantId=''; let categoryId=''; let createdProductId=''; let adminAgent:ReturnType<typeof request.agent>; let csrf='';
beforeAll(async()=>{const [admin,customer,variant,category]=await Promise.all([prisma.user.create({data:{email:adminEmail,passwordHash:await argon2.hash(password),role:'ADMIN'}}),prisma.user.create({data:{email:customerEmail,passwordHash:await argon2.hash(password)}}),prisma.productVariant.findFirstOrThrow({where:{status:'ACTIVE'}}),prisma.category.findFirstOrThrow({where:{isActive:true}})]);adminId=admin.id;customerId=customer.id;variantId=variant.id;categoryId=category.id;adminAgent=request.agent(app);const login=await adminAgent.post('/api/v1/auth/login').send({email:adminEmail,password});csrf=(login.headers['set-cookie'] as unknown as string[]).find(c=>c.startsWith(`${CSRF_COOKIE}=`))!.split(';')[0]!.split('=')[1]!;});
afterAll(async()=>{if(createdProductId) await prisma.$transaction([prisma.productCategory.deleteMany({where:{productId:createdProductId}}),prisma.product.delete({where:{id:createdProductId}})]);await prisma.auditLog.deleteMany({where:{actorId:{in:[adminId,customerId]}}});await prisma.inventoryMovement.deleteMany({where:{reason:'admin test correction'}});await prisma.session.deleteMany({where:{userId:{in:[adminId,customerId]}}});await prisma.user.deleteMany({where:{id:{in:[adminId,customerId]}}});});
describe('admin APIs',()=>{
  it('enforces unauthenticated 401, customer 403, and administrator access',async()=>{expect((await request(app).get('/api/v1/admin/dashboard')).status).toBe(401);const customer=request.agent(app);await customer.post('/api/v1/auth/login').send({email:customerEmail,password});expect((await customer.get('/api/v1/admin/dashboard')).status).toBe(403);const response=await adminAgent.get('/api/v1/admin/dashboard');expect(response.status).toBe(200);expect(response.body.data).toHaveProperty('totalProducts');});
  it('records an atomic admin correction as a movement and audit event',async()=>{const before=await prisma.productVariant.findUniqueOrThrow({where:{id:variantId}});const response=await adminAgent.post('/api/v1/admin/inventory/adjustments').set('X-CSRF-Token',csrf).send({variantId,quantity:1,type:'CORRECTION',reason:'admin test correction'});expect(response.status).toBe(200);expect((await prisma.productVariant.findUniqueOrThrow({where:{id:variantId}})).stockQuantity).toBe(before.stockQuantity+1);expect(await prisma.inventoryMovement.count({where:{variantId,reason:'admin test correction'}})).toBe(1);expect(await prisma.auditLog.count({where:{actorId:adminId,action:'INVENTORY_ADJUSTED'}})).toBe(1);await prisma.productVariant.update({where:{id:variantId},data:{stockQuantity:before.stockQuantity}});});
  it('returns the protected Phase 6 operational resources with paginated contracts',async()=>{for(const path of ['/api/v1/admin/variants','/api/v1/admin/inventory','/api/v1/admin/inventory/movements','/api/v1/admin/inventory/reservations','/api/v1/admin/audit-logs']){const response=await adminAgent.get(path);expect(response.status).toBe(200);expect(response.body.data).toMatchObject({items:expect.any(Array),page:1,limit:25});}const categories=await adminAgent.get('/api/v1/admin/categories');expect(categories.status).toBe(200);expect(categories.body.data).toEqual(expect.any(Array));const coupons=await adminAgent.get('/api/v1/admin/coupons');expect(coupons.status).toBe(200);expect(coupons.body.data).toEqual(expect.any(Array));});
  it('returns paginated and filtered inventory contracts with bounded limits',async()=>{const res=await adminAgent.get('/api/v1/admin/inventory?page=1&limit=10&filter=all');expect(res.status).toBe(200);expect(res.body.data).toMatchObject({items:expect.any(Array),page:1,limit:10,total:expect.any(Number),totalPages:expect.any(Number)});expect(res.body.data.items.length).toBeLessThanOrEqual(10);if(res.body.data.items.length>0){expect(res.body.data.items[0]).toHaveProperty('availableStock');expect(res.body.data.items[0]).toHaveProperty('sku');expect(res.body.data.items[0]).toHaveProperty('status');}});
  it('returns category relations on product mutations for the frontend mapper',async()=>{const slug=`admin-contract-${randomUUID().slice(0,8)}`;const created=await adminAgent.post('/api/v1/admin/products').set('X-CSRF-Token',csrf).send({name:'Admin contract product',slug,description:'A product used to verify the admin response contract.',basePricePaise:199900,categoryIds:[categoryId]});expect(created.status).toBe(201);createdProductId=created.body.data.id;expect(created.body.data.categories[0].category).toMatchObject({id:categoryId});const updated=await adminAgent.patch(`/api/v1/admin/products/${createdProductId}`).set('X-CSRF-Token',csrf).send({status:'ARCHIVED'});expect(updated.status).toBe(200);expect(updated.body.data.categories[0].category).toMatchObject({id:categoryId});});
});
