import { randomUUID } from 'node:crypto';
import { createServer } from 'node:http';
import { Pool } from 'pg';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { app } from '../../src/app.js';
import { env, getDatabaseUrl } from '../../src/config/env.js';
import * as databaseModule from '../../src/config/database.js';
import { REDACTED_PATHS } from '../../src/utils/logger.js';
import { boundedRouteLabel, metrics } from '../../src/utils/metrics.js';
import { ReservationCleanupWorker } from '../../src/services/reservation-worker.service.js';
import { aggregateMetricSnapshots } from '../../src/services/metrics-aggregation.service.js';
import { OperationalAlertService } from '../../src/services/operational-alert.service.js';
import { CommerceService } from '../../src/services/commerce.service.js';
import { PhonePeProvider } from '../../src/services/payment-provider.service.js';

describe('Phase 9 — Observability, Incident Response & Launch Validation', () => {
  const prisma = databaseModule.getPrismaClient();
  let testUserId = '';

  beforeAll(async () => {
    const user = await prisma.user.create({
      data: {
        email: `phase9-${randomUUID()}@example.invalid`,
        passwordHash: 'dummy-hash-phase9',
        firstName: 'Phase9',
        lastName: 'Tester',
        role: 'CUSTOMER',
        status: 'ACTIVE',
      },
    });
    testUserId = user.id;
  });

  afterAll(async () => {
    if (testUserId) {
      const orders = await prisma.order.findMany({ where: { userId: testUserId }, select: { id: true } });
      for (const o of orders) {
        await prisma.payment.deleteMany({ where: { orderId: o.id } });
        await prisma.order.delete({ where: { id: o.id } });
      }
      await prisma.user.deleteMany({ where: { id: testUserId } });
    }
  });

  beforeEach(() => {
    metrics.resetForTesting();
    vi.restoreAllMocks();
    ReservationCleanupWorker.resetInstanceForTesting();
  });

  // ---------------------------------------------------------------------------
  // 1. Request IDs propagate through successful responses
  // ---------------------------------------------------------------------------
  it('1. Request IDs propagate through successful responses', async () => {
    const customTraceId = `trace-${randomUUID()}`;
    const resWithCustomId = await request(app)
      .get('/healthz')
      .set('X-Request-Id', customTraceId);

    expect(resWithCustomId.status).toBe(200);
    expect(resWithCustomId.headers['x-request-id']).toBe(customTraceId);

    const resAutoGenerated = await request(app).get('/healthz');
    expect(resAutoGenerated.status).toBe(200);
    expect(resAutoGenerated.headers['x-request-id']).toBeDefined();
    expect(resAutoGenerated.headers['x-request-id']).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
    );
  });

  // ---------------------------------------------------------------------------
  // 2. Request IDs propagate through error responses and logs
  // ---------------------------------------------------------------------------
  it('2. Request IDs propagate through error responses and logs', async () => {
    const errorTraceId = `err-${randomUUID()}`;
    const res = await request(app)
      .post('/api/v1/auth/login')
      .set('X-Request-Id', errorTraceId)
      .send({ email: 'invalid-email', password: '123' });

    expect(res.status).toBe(400);
    expect(res.headers['x-request-id']).toBe(errorTraceId);
    expect(res.body.error).toBeDefined();
    expect(res.body.error.requestId).toBe(errorTraceId);
  });

  // ---------------------------------------------------------------------------
  // 3. Sensitive fields are redacted
  // ---------------------------------------------------------------------------
  it('3. Sensitive fields and callback signatures are included in redaction paths', () => {
    const requiredRedactedFields = [
      'password',
      'passwordConfirm',
      'token',
      'sessionToken',
      'csrfToken',
      'xVerify',
      'signature',
      'callbackPayload',
      'PHONEPE_CLIENT_SECRET',
      'cardNumber',
      'cvv',
    ];

    for (const field of requiredRedactedFields) {
      const isRedacted = REDACTED_PATHS.some(path => path === field || path.endsWith(`.${field}`));
      expect(isRedacted, `Field ${field} must be covered in REDACTED_PATHS`).toBe(true);
    }
  });

  // ---------------------------------------------------------------------------
  // 4. Readiness fails when migrations are pending
  // ---------------------------------------------------------------------------
  it('4. Readiness fails with HTTP 503 when migrations are pending in deployment environment', async () => {
    const originalEnv = env.NODE_ENV;
    (env as { NODE_ENV: string }).NODE_ENV = 'production';

    vi.spyOn(databaseModule, 'checkDatabaseReadiness').mockResolvedValueOnce({
      connected: true,
      migrationsReady: false,
    });

    try {
      const res = await request(app).get('/readyz');
      expect(res.status).toBe(503);
      expect(res.body.error.code).toBe('MIGRATIONS_PENDING');
    } finally {
      (env as { NODE_ENV: string }).NODE_ENV = originalEnv;
    }
  });

  // ---------------------------------------------------------------------------
  // 5. Readiness fails when the database is unavailable
  // ---------------------------------------------------------------------------
  it('5. Readiness fails with HTTP 503 when the database is unavailable or times out', async () => {
    vi.spyOn(databaseModule, 'checkDatabaseReadiness').mockResolvedValueOnce({
      connected: false,
      migrationsReady: false,
      reason: 'timeout',
    });

    const res = await request(app).get('/readyz');
    expect(res.status).toBe(503);
    expect(res.body.error.code).toBe('SERVICE_UNAVAILABLE');
    expect(res.body.error.message).toBe('Service is not ready.');
  });

  // ---------------------------------------------------------------------------
  // 6. Readiness reflects Redis degradation correctly
  // ---------------------------------------------------------------------------
  it('6. Readiness reflects Redis fallback gracefully without failing service readiness', async () => {
    vi.spyOn(databaseModule, 'checkDatabaseReadiness').mockResolvedValueOnce({
      connected: true,
      migrationsReady: true,
    });

    const res = await request(app).get('/readyz');
    expect(res.status).toBe(200);
    expect(res.body.data.status).toBe('ready');
    expect(['not_configured', 'connected', 'fallback_to_postgres']).toContain(
      res.body.data.checks.redis,
    );
  });

  // ---------------------------------------------------------------------------
  // 7. Background expiry processing cannot overlap unsafely
  // ---------------------------------------------------------------------------
  it('7. Background expiry processing cannot overlap unsafely in the same process', async () => {
    const worker = ReservationCleanupWorker.getInstance();
    const commerceService = (worker as unknown as { commerceService: CommerceService }).commerceService;

    let resolveFirstSweep!: (val: { releasedCount: number }) => void;
    const firstSweepPromise = new Promise<{ releasedCount: number }>(resolve => {
      resolveFirstSweep = resolve;
    });

    // Mock long-running sweep
    vi.spyOn(commerceService, 'releaseExpiredReservations').mockImplementationOnce(
      () => firstSweepPromise,
    );

    // Launch first sweep (async)
    const run1 = worker.runSweep();

    // Immediately launch second sweep while first is in progress
    const run2 = await worker.runSweep();

    expect(run2.releasedCount).toBe(0);
    expect(worker.getTelemetry().concurrencySkips).toBe(1);

    // Resolve first sweep
    resolveFirstSweep({ releasedCount: 3 });
    const res1 = await run1;

    expect(res1.releasedCount).toBe(3);
    expect(worker.getTelemetry().successfulSweeps).toBe(1);
    expect(worker.getTelemetry().totalReleasedReservations).toBe(3);
  });

  // ---------------------------------------------------------------------------
  // 8. Database lock coordinates multiple application instances
  // ---------------------------------------------------------------------------
  it('8. Reservation expiry uses a PostgreSQL transaction lock across instances', async () => {
    const lockPool = new Pool({ connectionString: getDatabaseUrl(), max: 1 });
    const lockClient = await lockPool.connect();
    try {
      await lockClient.query('BEGIN');
      await lockClient.query("SELECT pg_advisory_xact_lock(hashtext('purvaja:reservation-expiry'))");

      const result = await new CommerceService().releaseExpiredReservations();

      expect(result.releasedCount).toBe(0);
      expect(result.skippedDueToDistributedLock).toBe(true);
      await lockClient.query('ROLLBACK');
    } finally {
      lockClient.release();
      await lockPool.end();
    }
  });

  // ---------------------------------------------------------------------------
  // 9. Worker failures are observable and recoverable
  // ---------------------------------------------------------------------------
  it('9. Worker failures are logged, tracked in metrics, and recover on subsequent ticks', async () => {
    const worker = ReservationCleanupWorker.getInstance();
    const commerceService = (worker as unknown as { commerceService: CommerceService }).commerceService;

    // Fail first sweep
    vi.spyOn(commerceService, 'releaseExpiredReservations')
      .mockRejectedValueOnce(new Error('Transient DB lock serialization error'))
      .mockRejectedValueOnce(new Error('Transient DB lock serialization error'))
      .mockRejectedValueOnce(new Error('Transient DB lock serialization error'));

    const failedRun = await worker.runSweep();
    expect(failedRun.releasedCount).toBe(0);
    expect(worker.getTelemetry().failedSweeps).toBe(1);

    // Succeed on second sweep
    vi.spyOn(commerceService, 'releaseExpiredReservations').mockResolvedValueOnce({
      releasedCount: 5,
    });

    const successRun = await worker.runSweep();
    expect(successRun.releasedCount).toBe(5);
    expect(worker.getTelemetry().failedSweeps).toBe(1);
    expect(worker.getTelemetry().successfulSweeps).toBe(1);
    expect(worker.getTelemetry().totalReleasedReservations).toBe(5);
  });

  // ---------------------------------------------------------------------------
  // 9. Duplicate payment callbacks remain idempotent
  // ---------------------------------------------------------------------------
  it('9. Duplicate payment callbacks remain idempotent and return existing state', async () => {
    const order = await prisma.order.create({
      data: {
        userId: testUserId,
        orderNumber: `P9-ORD-${randomUUID().slice(0, 8)}`,
        status: 'CONFIRMED',
        paymentStatus: 'SUCCESS',
        subtotalPaise: 5000,
        discountPaise: 0,
        shippingChargePaise: 0,
        totalPaise: 5000,
        shippingAddress: { city: 'Test' },
      },
    });
    const payment = await prisma.payment.create({
      data: {
        orderId: order.id,
        provider: 'PHONEPE',
        method: 'UPI',
        amountPaise: 5000,
        status: 'SUCCESS',
        idempotencyKey: randomUUID(),
      },
    });

    const commerce = new CommerceService();
    const result = await commerce.reconcilePayment(payment.id, 'admin-1');

    expect(result.reconciled).toBe(false);
    expect(result.previousStatus).toBe('SUCCESS');
    expect(result.newStatus).toBe('SUCCESS');
    expect(result.details).toContain('already in a confirmed successful state');

    // Cleanup
    await prisma.payment.deleteMany({ where: { orderId: order.id } });
    await prisma.order.delete({ where: { id: order.id } });
  });

  // ---------------------------------------------------------------------------
  // 10. Payment/order mismatches are rejected and audited
  // ---------------------------------------------------------------------------
  it('10. Payment captured after reservation expiry creates a refund while preserving restocked inventory', async () => {
    const order = await prisma.order.create({
      data: {
        userId: testUserId,
        orderNumber: `P9-ORD-${randomUUID().slice(0, 8)}`,
        status: 'CANCELLED',
        paymentStatus: 'EXPIRED',
        subtotalPaise: 4500,
        discountPaise: 0,
        shippingChargePaise: 0,
        totalPaise: 4500,
        shippingAddress: { city: 'Test' },
      },
    });
    const payment = await prisma.payment.create({
      data: {
        orderId: order.id,
        provider: 'PHONEPE',
        method: 'UPI',
        amountPaise: 4500,
        status: 'EXPIRED',
        idempotencyKey: randomUUID(),
      },
    });

    const origProvider = env.PAYMENT_PROVIDER;
    (env as { PAYMENT_PROVIDER: string }).PAYMENT_PROVIDER = 'phonepe';
    const checkSpy = vi
      .spyOn(PhonePeProvider.prototype, 'checkStatus')
      .mockResolvedValueOnce({
        state: 'COMPLETED',
        amountPaise: 4500,
        merchantTransactionId: payment.id,
        responseCode: 'SUCCESS',
      });

    try {
      const commerce = new CommerceService();
      const result = await commerce.reconcilePayment(payment.id);

      expect(result.reconciled).toBe(true);
      expect(result.newStatus).toBe('SUCCESS');
      expect(result.details).toContain('Late capture recorded');
      expect(await prisma.paymentRefund.findFirst({ where: { paymentId: payment.id } }))
        .toMatchObject({ status: 'REQUESTED', mode: 'LIVE', reason: 'LATE_CAPTURE', amountPaise: 4500 });
      expect(metrics.getSnapshot().business.payments.mismatches).toBeGreaterThanOrEqual(1);
    } finally {
      (env as { PAYMENT_PROVIDER: string }).PAYMENT_PROVIDER = origProvider;
      checkSpy.mockRestore();
      await prisma.paymentObservation.deleteMany({ where: { paymentId: payment.id } });
      await prisma.paymentRefund.deleteMany({ where: { paymentId: payment.id } });
      await prisma.payment.deleteMany({ where: { orderId: order.id } });
      await prisma.order.delete({ where: { id: order.id } });
    }
  });

  // ---------------------------------------------------------------------------
  // 11. Failed reconciliation does not alter inventory incorrectly
  // ---------------------------------------------------------------------------
  it('11. Failed reconciliation safely transitions payment and order to FAILED/CANCELLED', async () => {
    const order = await prisma.order.create({
      data: {
        userId: testUserId,
        orderNumber: `P9-ORD-${randomUUID().slice(0, 8)}`,
        status: 'PENDING',
        paymentStatus: 'INITIATED',
        subtotalPaise: 6000,
        discountPaise: 0,
        shippingChargePaise: 0,
        totalPaise: 6000,
        shippingAddress: { city: 'Test' },
      },
    });
    const payment = await prisma.payment.create({
      data: {
        orderId: order.id,
        provider: 'PHONEPE',
        method: 'UPI',
        amountPaise: 6000,
        status: 'INITIATED',
        idempotencyKey: randomUUID(),
      },
    });

    const origProvider = env.PAYMENT_PROVIDER;
    (env as { PAYMENT_PROVIDER: string }).PAYMENT_PROVIDER = 'phonepe';
    const checkSpy = vi
      .spyOn(PhonePeProvider.prototype, 'checkStatus')
      .mockResolvedValueOnce({
        state: 'FAILED',
        amountPaise: 6000,
        merchantTransactionId: payment.id,
        responseCode: 'PAYMENT_ERROR',
      });

    try {
      const commerce = new CommerceService();
      const result = await commerce.reconcilePayment(payment.id);
      expect(result.paymentId).toBe(payment.id);
      expect(result.previousStatus).toBe('INITIATED');
      expect(result.newStatus).toBe('FAILED');
      expect(result.reconciled).toBe(true);
      expect(result.details).toContain('Payment marked failed and reservations released');
    } finally {
      (env as { PAYMENT_PROVIDER: string }).PAYMENT_PROVIDER = origProvider;
      checkSpy.mockRestore();
      await prisma.payment.deleteMany({ where: { orderId: order.id } });
      await prisma.order.delete({ where: { id: order.id } });
    }
  });

  // ---------------------------------------------------------------------------
  // 12. Graceful shutdown stops workers and closes dependencies
  // ---------------------------------------------------------------------------
  it('12. Graceful shutdown cleanly stops background workers', () => {
    const worker = ReservationCleanupWorker.getInstance();
    worker.start(30_000);
    expect(worker.isRunning()).toBe(true);

    worker.stop();
    expect(worker.isRunning()).toBe(false);
  });

  // ---------------------------------------------------------------------------
  // 13. Restart does not duplicate workers
  // ---------------------------------------------------------------------------
  it('13. Starting the worker multiple times ignores duplicates without spawning timers', () => {
    const worker = ReservationCleanupWorker.getInstance();
    worker.start(60_000);
    expect(worker.isRunning()).toBe(true);

    // Second start invocation
    worker.start(60_000);
    expect(worker.isRunning()).toBe(true);

    worker.stop();
    expect(worker.isRunning()).toBe(false);
  });

  // ---------------------------------------------------------------------------
  // 14. External smoke tests target the deployed HTTP service
  // ---------------------------------------------------------------------------
  it('14. Smoke test suite supports real network targets via SMOKE_BASE_URL', () => {
    const originalUrl = process.env.SMOKE_BASE_URL;
    process.env.SMOKE_BASE_URL = 'http://127.0.0.1:5001';

    const target = process.env.SMOKE_BASE_URL?.trim() || app;
    expect(target).toBe('http://127.0.0.1:5001');

    if (originalUrl) process.env.SMOKE_BASE_URL = originalUrl;
    else delete process.env.SMOKE_BASE_URL;
  });

  // ---------------------------------------------------------------------------
  // 15. Operational metrics snapshot structure verification
  // ---------------------------------------------------------------------------
  it('15. Operational metrics registry accurately aggregates HTTP and business statistics', () => {
    metrics.requestStarted();
    metrics.requestCompleted('/api/v1/products', 200, 45);
    metrics.requestStarted();
    metrics.requestCompleted('/api/v1/checkout', 500, 120);

    metrics.recordCheckoutAttempt();
    metrics.recordCheckoutSuccess();
    metrics.recordPaymentInitiated();
    metrics.recordPaymentSucceeded();

    const snapshot = metrics.getSnapshot();

    expect(snapshot.http.totalRequests).toBe(2);
    expect(snapshot.http.status2xx).toBe(1);
    expect(snapshot.http.status5xx).toBe(1);
    expect(snapshot.http.latency.count).toBe(2);
    expect(snapshot.http.byRoute['/api/v1/products'].count).toBe(1);
    expect(snapshot.business.checkout.attempts).toBe(1);
    expect(snapshot.business.checkout.successes).toBe(1);
    expect(snapshot.business.payments.initiated).toBe(1);
    expect(snapshot.business.payments.succeeded).toBe(1);
  });

  it('16. Route metrics use matched patterns and remain bounded under hostile URL cardinality', async () => {
    const productId = randomUUID();
    await request(app).get(`/api/v1/products/${productId}`);
    const afterRequest = metrics.getSnapshot();
    expect(afterRequest.http.byRoute['/api/v1/products/:slugOrId']).toBeDefined();
    expect(JSON.stringify(afterRequest.http.byRoute)).not.toContain(productId);

    metrics.resetForTesting();
    for (let index = 0; index < 250; index++) {
      metrics.requestStarted();
      metrics.requestCompleted(`/unmatched/${index}-${randomUUID()}`, 404, 1);
    }
    const routes = Object.keys(metrics.getSnapshot().http.byRoute);
    expect(routes.length).toBeLessThanOrEqual(100);
    expect(routes).toContain('__other__');
    expect(boundedRouteLabel({ originalUrl: `/reset/${productId}?token=secret` })).toBe('/reset/:value');
  });

  it('17. Worker snapshots aggregate counters and weighted route latency across processes', () => {
    metrics.requestStarted();
    metrics.requestCompleted('/api/v1/products', 200, 20);
    const workerOne = metrics.getSnapshot();
    metrics.resetForTesting();
    metrics.requestStarted();
    metrics.requestCompleted('/api/v1/products', 500, 80);
    metrics.recordWorkerSweepStart();
    metrics.recordWorkerSweepFailed(25);
    const workerTwo = metrics.getSnapshot();

    const aggregate = aggregateMetricSnapshots([workerOne, workerTwo]);
    expect(aggregate.http.totalRequests).toBe(2);
    expect(aggregate.http.byRoute['/api/v1/products']).toEqual({ count: 2, errors: 1, avgMs: 50 });
    expect(aggregate.worker.failedSweeps).toBe(1);
  });

  it('18. Injected operational failures reach the configured alert destination and deduplicate', async () => {
    const received: unknown[] = [];
    const receiver = createServer((req, res) => {
      let body = '';
      req.on('data', chunk => { body += String(chunk); });
      req.on('end', () => { received.push(JSON.parse(body)); res.writeHead(202).end(); });
    });
    await new Promise<void>(resolve => receiver.listen(0, '127.0.0.1', resolve));
    const address = receiver.address();
    if (!address || typeof address === 'string') throw new Error('Alert receiver did not bind to a TCP port.');
    try {
      const alerts = new OperationalAlertService(`http://127.0.0.1:${address.port}/alerts`, 'test-alert-token-12345', 60_000);
      const alert = { code: 'DATA_CONSISTENCY_DRIFT' as const, severity: 'critical' as const, summary: 'Injected Phase 9 alert.' };
      expect(await alerts.deliver(alert, 'injected-drift')).toMatchObject({ status: 'delivered', statusCode: 202 });
      expect(await alerts.deliver(alert, 'injected-drift')).toMatchObject({ status: 'deduplicated' });
      expect(received).toHaveLength(1);
      expect(received[0]).toMatchObject({ code: 'DATA_CONSISTENCY_DRIFT', severity: 'critical' });
    } finally {
      await new Promise<void>((resolve, reject) => receiver.close(error => error ? reject(error) : resolve()));
    }
  });

  it('19. A worker that misses three completion intervals is detected as stalled', async () => {
    const worker = ReservationCleanupWorker.getInstance();
    worker.start(10_000);
    expect(await worker.checkForStall(Date.now() + 30_001)).toBe(true);
    worker.stop();
  });
});
