import type { RequestHandler } from 'express';
import { AdminService } from '../services/admin.service.js';
import { adjustment, category, coupon, input, inventoryQuery, orderStatus, pagination, product, stockCorrection, uuid, variant } from '../validators/admin.validator.js';
const admin=new AdminService(); const send=(res:Parameters<RequestHandler>[1],data:unknown,status=200)=>res.status(status).json({success:true,data}); const id=(value:string|string[]|undefined)=>input(uuid,typeof value==='string'?value:'');
export const dashboard:RequestHandler=async(_q,res,next)=>{try{send(res,await admin.dashboard());}catch(e){next(e);}};
export const products:RequestHandler=async(req,res,next)=>{try{send(res,await admin.products(input(pagination,req.query)));}catch(e){next(e);}};
export const productDetail:RequestHandler=async(req,res,next)=>{try{send(res,await admin.product(id(req.params.id)));}catch(e){next(e);}};
export const createProduct:RequestHandler=async(req,res,next)=>{try{send(res,await admin.createProduct(req.auth!.userId,input(product,req.body)),201);}catch(e){next(e);}};
export const updateProduct:RequestHandler=async(req,res,next)=>{try{send(res,await admin.updateProduct(req.auth!.userId,id(req.params.id),input(product.partial(),req.body)));}catch(e){next(e);}};
export const categories:RequestHandler=async(_q,res,next)=>{try{send(res,await admin.categories());}catch(e){next(e);}};
export const createCategory:RequestHandler=async(req,res,next)=>{try{send(res,await admin.createCategory(req.auth!.userId,input(category,req.body)),201);}catch(e){next(e);}};
export const updateCategory:RequestHandler=async(req,res,next)=>{try{send(res,await admin.updateCategory(req.auth!.userId,id(req.params.id),input(category.partial(),req.body)));}catch(e){next(e);}};
export const variants:RequestHandler=async(req,res,next)=>{try{send(res,await admin.variants(input(pagination,req.query)));}catch(e){next(e);}};
export const createVariant:RequestHandler=async(req,res,next)=>{try{send(res,await admin.createVariant(req.auth!.userId,input(variant,req.body)),201);}catch(e){next(e);}};
export const updateVariant:RequestHandler=async(req,res,next)=>{try{send(res,await admin.updateVariant(req.auth!.userId,id(req.params.id),input(variant.partial(),req.body)));}catch(e){next(e);}};
export const inventory:RequestHandler=async(req,res,next)=>{try{send(res,await admin.inventory(input(inventoryQuery,req.query)));}catch(e){next(e);}};
export const movements:RequestHandler=async(req,res,next)=>{try{send(res,await admin.movements(input(pagination,req.query)));}catch(e){next(e);}};
export const reservations:RequestHandler=async(req,res,next)=>{try{send(res,await admin.reservations(input(pagination,req.query)));}catch(e){next(e);}};
export const adjust:RequestHandler=async(req,res,next)=>{try{send(res,await admin.adjust(req.auth!.userId,input(adjustment,req.body)));}catch(e){next(e);}};
export const setStock:RequestHandler=async(req,res,next)=>{try{const value=input(stockCorrection,req.body);send(res,await admin.setStock(req.auth!.userId,id(req.params.id),value.stock));}catch(e){next(e);}};
export const orders:RequestHandler=async(req,res,next)=>{try{send(res,await admin.orders(input(pagination,req.query)));}catch(e){next(e);}};
export const orderDetail:RequestHandler=async(req,res,next)=>{try{send(res,await admin.order(id(req.params.id)));}catch(e){next(e);}};
export const updateOrder:RequestHandler=async(req,res,next)=>{try{send(res,await admin.updateOrderStatus(req.auth!.userId,id(req.params.id),input(orderStatus,req.body).status));}catch(e){next(e);}};
export const customers:RequestHandler=async(req,res,next)=>{try{send(res,await admin.customers(input(pagination,req.query)));}catch(e){next(e);}};
export const customerDetail:RequestHandler=async(req,res,next)=>{try{send(res,await admin.customer(id(req.params.id)));}catch(e){next(e);}};
export const coupons:RequestHandler=async(_q,res,next)=>{try{send(res,await admin.coupons());}catch(e){next(e);}};
export const createCoupon:RequestHandler=async(req,res,next)=>{try{send(res,await admin.createCoupon(req.auth!.userId,input(coupon,req.body)),201);}catch(e){next(e);}};
export const updateCoupon:RequestHandler=async(req,res,next)=>{try{send(res,await admin.updateCoupon(req.auth!.userId,id(req.params.id),input(coupon.partial(),req.body)));}catch(e){next(e);}};
export const auditLogs:RequestHandler=async(req,res,next)=>{try{send(res,await admin.auditLogs(input(pagination,req.query)));}catch(e){next(e);}};
